"""classes

Revision ID: 21255a33ea41
Revises: 
Create Date: 2024-01-24 14:45:55.867779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21255a33ea41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mountains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('completed', sa.String(), nullable=False),
    sa.Column('climber_id', sa.Integer(), nullable=True),
    sa.Column('mountain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['climber_id'], ['climbers.id'], name=op.f('fk_badges_climber_id_climbers')),
    sa.ForeignKeyConstraint(['mountain_id'], ['mountains.id'], name=op.f('fk_badges_mountain_id_mountains')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badges')
    op.drop_table('mountains')
    op.drop_table('climbers')
    # ### end Alembic commands ###
